coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
    patch:
      default:
        target: auto
        threshold: 1%
        base: auto

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "**/*.test.{ts,tsx}"
  - "**/*.spec.{ts,tsx}"
  - "**/mocks/**"
  - "**/coverage/**"
  - "**/*.config.{ts,js}"
  - "src/setupTests.ts"
  - "src/vite-env.d.ts"
  - "public/**"
